services:
  database:
    image: postgres:17-alpine
    container_name: payment-checkout-postgres
    environment:
      POSTGRES_DB: payment_checkout
      POSTGRES_USER: payment_user
      POSTGRES_PASSWORD: payment_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U payment_user -d payment_checkout"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data:
